-- Active: 1709043130692@@127.0.0.1@3306@mysql
DROP DATABASE IF EXISTS Biblioteca;
CREATE DATABASE Biblioteca;

USE Biblioteca;

-- TABLA DE ROLES
CREATE TABLE Rol (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL
);

-- TABLA DE USUARIOS
CREATE TABLE Usuario (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Email VARCHAR(200) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    RolId INT NOT NULL DEFAULT 2,
    FOREIGN KEY (RolId) REFERENCES Rol(Id)
);

-- CATÁLOGO GENERAL DE LIBROS (LO CREA SOLO EL ADMIN)
CREATE TABLE CatalogoLibro (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Titulo VARCHAR(200) NOT NULL,
    Autor VARCHAR(200) NOT NULL,
    Anio INT,
    Descripcion TEXT
);

CREATE TABLE Libro ( 
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Titulo VARCHAR(200) NOT NULL,
    Autor VARCHAR(200) NOT NULL,
    Anio INT, Descripcion TEXT,
    UsuarioId INT,
    FOREIGN KEY (UsuarioId) REFERENCES Usuario(Id)
);
